define(['ui/utils'], function(uiUtils){
	
	uiUtils.setDfeCustomStyle('.css-loading-anim-circle{position:relative;width:125px;height:125px;margin:auto;transform:scale(0.6);-o-transform:scale(0.6);-ms-transform:scale(0.6);-webkit-transform:scale(0.6);-moz-transform:scale(0.6)}.f_circleG{position:absolute;background-color:#fff;height:22px;width:22px;border-radius:12px;-o-border-radius:12px;-ms-border-radius:12px;-webkit-border-radius:12px;-moz-border-radius:12px;animation-name:f_fadeG;-o-animation-name:f_fadeG;-ms-animation-name:f_fadeG;-webkit-animation-name:f_fadeG;-moz-animation-name:f_fadeG;animation-duration:1.2s;-o-animation-duration:1.2s;-ms-animation-duration:1.2s;-webkit-animation-duration:1.2s;-moz-animation-duration:1.2s;animation-iteration-count:infinite;-o-animation-iteration-count:infinite;-ms-animation-iteration-count:infinite;-webkit-animation-iteration-count:infinite;-moz-animation-iteration-count:infinite;animation-direction:normal;-o-animation-direction:normal;-ms-animation-direction:normal;-webkit-animation-direction:normal;-moz-animation-direction:normal}.frotateG_01{left:0;top:51px;animation-delay:.45s;-o-animation-delay:.45s;-ms-animation-delay:.45s;-webkit-animation-delay:.45s;-moz-animation-delay:.45s}.frotateG_02{left:15px;top:15px;animation-delay:.6s;-o-animation-delay:.6s;-ms-animation-delay:.6s;-webkit-animation-delay:.6s;-moz-animation-delay:.6s}.frotateG_03{left:51px;top:0;animation-delay:.75s;-o-animation-delay:.75s;-ms-animation-delay:.75s;-webkit-animation-delay:.75s;-moz-animation-delay:.75s}.frotateG_04{right:15px;top:15px;animation-delay:.9s;-o-animation-delay:.9s;-ms-animation-delay:.9s;-webkit-animation-delay:.9s;-moz-animation-delay:.9s}.frotateG_05{right:0;top:51px;animation-delay:1.05s;-o-animation-delay:1.05s;-ms-animation-delay:1.05s;-webkit-animation-delay:1.05s;-moz-animation-delay:1.05s}.frotateG_06{right:15px;bottom:15px;animation-delay:1.2s;-o-animation-delay:1.2s;-ms-animation-delay:1.2s;-webkit-animation-delay:1.2s;-moz-animation-delay:1.2s}.frotateG_07{left:51px;bottom:0;animation-delay:1.35s;-o-animation-delay:1.35s;-ms-animation-delay:1.35s;-webkit-animation-delay:1.35s;-moz-animation-delay:1.35s}.frotateG_08{left:15px;bottom:15px;animation-delay:1.5s;-o-animation-delay:1.5s;-ms-animation-delay:1.5s;-webkit-animation-delay:1.5s;-moz-animation-delay:1.5s}@keyframes f_fadeG{0%{background-color:#000}100%{background-color:#fff}}@-o-keyframes f_fadeG{0%{background-color:#000}100%{background-color:#fff}}@-ms-keyframes f_fadeG{0%{background-color:#000}100%{background-color:#fff}}@-webkit-keyframes f_fadeG{0%{background-color:#000}100%{background-color:#fff}}@-moz-keyframes f_fadeG{0%{background-color:#000}100%{background-color:#fff}}', 'loader-anim-circle');
	uiUtils.setDfeCustomStyle(".css-arrow,.css-arrow *{pointer-events:none} .css-arrow{width:16px; height:16px;}.css-arrow-i-,.css-arrow-i-right{transform:scale(0.66, 0.5)}.css-arrow-i-down{transform: rotate(90deg)scale(0.66, 0.5);-ms-transform: rotate(90deg) scale(0.66, 0.5) translate(1px, -4px)}.css-arrow-i-left{transform: rotate(180deg)scale(0.66, 0.5)}.css-arrow-i-up{transform: rotate(270deg)scale(0.66, 0.5);-ms-transform: rotate(270deg) scale(0.66, 0.5) translate(1px, -4px)}.css-arrow-i{width:24px;height:24px}.css-arrow,.css-arrow-i{display:flex;align-items:center;justify-content:center;flex-direction:column}.css-arrow-i > div{position:relative;height:0;width:0;border:12px solid;border-bottom-color:transparent!important;border-left-color:transparent!important;-webkit-transform:rotate(45deg);transform:rotate(45deg);border-radius:4px}.css-arrow-i i{position:absolute;top:-1px;right:-1px;display:block;border:7px solid grey;-webkit-transform:rotate(-45deg) translate(2px,1px);transform:rotate(-45deg) translate(2px,1px);border-radius:4px 0 0 4px;width:3px}", 'css-arrow-i-vector');
	uiUtils.setDfeCustomStyle(".css-minus{width:10px;height:10px;position:relative}.css-minus::before{content:'';border-top:2px solid;border-color:inherit;width:100%;position:absolute;top:calc(50% - 1px);left:0px}.css-plus{width:10px;height:10px;position:relative}.css-plus::before{content:'';border-top:2px solid;border-color:inherit;width:100%;position:absolute;top:calc(50% - 1px);left:0px}.css-plus::after{content:'';border-left:2px solid;border-color:inherit;height:100%;position:absolute;left:calc(50% - 1px)}.css-pm-button{width:100%; height:100%;display:flex;align-items:center;justify-content:center;flex-direction:column}.css-pm-button > div{display:inline-flex;border:1px solid #add8e6;border-radius:3px;background:linear-gradient(to top left,lightblue,lightcyan);border-color:#add8e6 #a9a9a9 #a9a9a9 #add8e6}.css-pm-button *{pointer-events:none}.css-pm-button:active > div{background:linear-gradient(to top left,lightcyan,lightblue);border-color:#a9a9a9 #add8e6 #add8e6 #a9a9a9}", 'css-signs-vector');
	return {	loadingCircles: function(){
					return '<div class="css-loading-anim-circle"><div class="f_circleG frotateG_01"></div><div class="f_circleG frotateG_02"></div><div class="f_circleG frotateG_03"></div><div class="f_circleG frotateG_04"></div><div class="f_circleG frotateG_05"></div><div class="f_circleG frotateG_06"></div><div class="f_circleG frotateG_07"></div><div class="f_circleG frotateG_08"></div></div>'
				},
			 	arrow: function(color,direction) {
			 		color = color||'inherit', direction=direction||'';
			 		return '<div class="css-arrow"><div class="css-arrow-i css-arrow-i-' + direction + '"><div style="border-color: ' + color + '"><i style="border-color: ' + color + '; background: ' + color + ';"></i></div></div></div>';
			 	},
			 	sign: function(sign, color) {
			 		return '<div class="css-pm-button"><div><div class="css-' + sign + '" style="border-color: ' + (color||'grey') + ';"></div></div></div>';
			 	}
	       }
})
